namespace Jellyfin.Plugin.JellyNotify.Services;

/// <summary>
/// Localized title/message text for real event notifications (request approved,
/// download started, media available, etc.) generated by <c>MediaRequestService</c>
/// (Seerr-driven) and <c>ArrSyncService</c> (Sonarr/Radarr-driven). Callers resolve
/// the target user's effective language via <see cref="NotificationLanguage"/> and
/// pass it in here — this class does not know about preferences or "auto" itself.
/// </summary>
public static class NotificationText
{
    /// <summary>"Your request for X is being processed" — a new Seerr request was just registered.</summary>
    public static (string Title, string Message) RequestCreated(string mediaTitle, string language)
    {
        var (es, ca) = Flags(language);
        return ca
            ? ("Sol·licitud registrada", $"La teva sol·licitud de \"{mediaTitle}\" s'està processant.")
            : es
                ? ("Solicitud registrada", $"Tu solicitud de \"{mediaTitle}\" está siendo procesada.")
                : ("Request registered", $"Your request for \"{mediaTitle}\" is being processed.");
    }

    /// <summary>A pending Seerr request was approved.</summary>
    public static (string Title, string Message) RequestApproved(string mediaTitle, string language)
    {
        var (es, ca) = Flags(language);
        return ca
            ? ("Sol·licitud aprovada", $"La teva sol·licitud de \"{mediaTitle}\" ha estat aprovada.")
            : es
                ? ("Solicitud aprobada", $"Tu solicitud de \"{mediaTitle}\" ha sido aprobada.")
                : ("Request approved", $"Your request for \"{mediaTitle}\" has been approved.");
    }

    /// <summary>A Seerr request was declined.</summary>
    public static (string Title, string Message) RequestDeclined(string mediaTitle, string language)
    {
        var (es, ca) = Flags(language);
        return ca
            ? ("Sol·licitud rebutjada", $"La teva sol·licitud de \"{mediaTitle}\" ha estat rebutjada.")
            : es
                ? ("Solicitud rechazada", $"Tu solicitud de \"{mediaTitle}\" ha sido rechazada.")
                : ("Request declined", $"Your request for \"{mediaTitle}\" has been declined.");
    }

    /// <summary>A Seerr request failed.</summary>
    public static (string Title, string Message) RequestFailed(string mediaTitle, string language)
    {
        var (es, ca) = Flags(language);
        return ca
            ? ("Sol·licitud fallida", $"La teva sol·licitud de \"{mediaTitle}\" ha fallat.")
            : es
                ? ("Solicitud fallida", $"Tu solicitud de \"{mediaTitle}\" ha fallado.")
                : ("Request failed", $"Your request for \"{mediaTitle}\" has failed.");
    }

    /// <summary>Media became fully available in the library.</summary>
    public static (string Title, string Message) MediaAvailable(string mediaTitle, string language)
    {
        var (es, ca) = Flags(language);
        return ca
            ? ("Contingut disponible", $"\"{mediaTitle}\" ja està disponible a la teva biblioteca.")
            : es
                ? ("Contenido disponible", $"\"{mediaTitle}\" ya está disponible en tu biblioteca.")
                : ("Media available", $"\"{mediaTitle}\" is now available in your library.");
    }

    /// <summary>Media became partially available (e.g. some episodes of a season).</summary>
    public static (string Title, string Message) MediaPartiallyAvailable(string mediaTitle, string language)
    {
        var (es, ca) = Flags(language);
        return ca
            ? ("Contingut parcialment disponible", $"\"{mediaTitle}\" està parcialment disponible.")
            : es
                ? ("Contenido parcialmente disponible", $"\"{mediaTitle}\" está parcialmente disponible.")
                : ("Media partially available", $"\"{mediaTitle}\" is partially available.");
    }

    /// <summary>Seerr reported the media as blocklisted/deleted.</summary>
    public static (string Title, string Message) ProblemDetected(string mediaTitle, string language)
    {
        var (es, ca) = Flags(language);
        return ca
            ? ("Problema detectat", $"S'ha detectat un problema amb \"{mediaTitle}\".")
            : es
                ? ("Problema detectado", $"Se ha detectado un problema con \"{mediaTitle}\".")
                : ("Problem detected", $"A problem was detected for \"{mediaTitle}\".");
    }

    /// <summary>A Sonarr/Radarr queue item began transferring for real (progress &gt; 0 with an ETA), seen on the queue poll — not the bare grab.</summary>
    public static (string Title, string Message) ArrDownloadStarted(string mediaTitle, string language)
    {
        var (es, ca) = Flags(language);
        return ca
            ? ("Descàrrega iniciada", $"\"{mediaTitle}\" s'està descarregant.")
            : es
                ? ("Descarga iniciada", $"\"{mediaTitle}\" se está descargando.")
                : ("Download started", $"\"{mediaTitle}\" is now downloading.");
    }

    /// <summary>A Sonarr/Radarr download crossed the configured progress threshold — the mid-download "Downloading" ping.</summary>
    public static (string Title, string Message) ArrDownloading(string mediaTitle, string language)
    {
        var (es, ca) = Flags(language);
        return ca
            ? ("Descarregant", $"\"{mediaTitle}\" s'està descarregant.")
            : es
                ? ("Descargando", $"\"{mediaTitle}\" se está descargando.")
                : ("Downloading", $"\"{mediaTitle}\" is downloading.");
    }

    /// <summary>A Sonarr/Radarr download failed.</summary>
    public static (string Title, string Message) ArrDownloadFailed(string mediaTitle, string language)
    {
        var (es, ca) = Flags(language);
        return ca
            ? ("Descàrrega fallida", $"La descàrrega de \"{mediaTitle}\" ha fallat.")
            : es
                ? ("Descarga fallida", $"La descarga de \"{mediaTitle}\" ha fallado.")
                : ("Download failed", $"Download of \"{mediaTitle}\" has failed.");
    }

    /// <summary>A Sonarr/Radarr download reported a warning (e.g. stalled).</summary>
    public static (string Title, string Message) ArrDownloadWarning(string mediaTitle, string language)
    {
        var (es, ca) = Flags(language);
        return ca
            ? ("Avís de descàrrega", $"Avís a la descàrrega de \"{mediaTitle}\".")
            : es
                ? ("Aviso de descarga", $"Aviso en la descarga de \"{mediaTitle}\".")
                : ("Download warning", $"Warning on download of \"{mediaTitle}\".");
    }

    private static (bool IsSpanish, bool IsCatalan) Flags(string language) => (
        string.Equals(language, "es-ES", System.StringComparison.OrdinalIgnoreCase),
        string.Equals(language, "ca", System.StringComparison.OrdinalIgnoreCase));
}
