namespace Jellyfin.Plugin.JellyNotify.Models;

/// <summary>
/// Defines the types of notifications that can be generated by JellyNotify.
/// </summary>
public enum NotificationType
{
    /// <summary>A new media request has been created.</summary>
    RequestCreated,

    /// <summary>A media request has been approved.</summary>
    RequestApproved,

    /// <summary>A media request has been declined.</summary>
    RequestDeclined,

    /// <summary>A media request has failed processing.</summary>
    RequestFailed,

    /// <summary>A download has started for requested media.</summary>
    DownloadStarted,

    /// <summary>Download progress update.</summary>
    DownloadProgress,

    /// <summary>A warning occurred during download.</summary>
    DownloadWarning,

    /// <summary>A download has failed.</summary>
    DownloadFailed,

    /// <summary>A download has been imported into the media library. No longer generated — MediaAvailable covers this. Kept (not removed/reordered) because <see cref="NotificationType"/> is persisted as its numeric ordinal, not as a string; removing a member would shift every later value and silently reinterpret already-stored history.</summary>
    [Obsolete("No longer generated — MediaAvailable covers this case.")]
    DownloadImported,

    /// <summary>Requested media is now fully available.</summary>
    MediaAvailable,

    /// <summary>Requested media is partially available (e.g., some seasons/episodes).</summary>
    MediaPartiallyAvailable,

    /// <summary>A warning has been raised on a media issue.</summary>
    IssueWarning,

    /// <summary>A media issue has been resolved.</summary>
    IssueResolved,

    /// <summary>A test notification for verifying channel configuration.</summary>
    TestNotification
}
